site_name: vs.xml
repo_url: https://github.com/lazy-eggplant/vs.xml
site_dir: ../website/docs
docs_dir: ../../docs

theme:
  name: material
  custom_dir: ./
  logo:
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.tilde
  - pymdownx.tasklist
  - mdx_truly_sane_lists
  - sane_lists
  - smarty
  - toc:
      permalink: "#"
plugins:
  - search
  - gh-admonitions
