name: Building & Testing
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-build
  cancel-in-progress: true

on:
  workflow_call:
  push:
    branches: [master]
    paths:
      - "**"
      - "!**.md"

  pull_request:
    branches: [master]
    paths:
      - "**"
      - "!**.md"

jobs:
  build-all:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Configure and test
        run: |
          xmake f -m release --with_tests=y -y
          xmake -y
          xmake test -y

  build-noexcept:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build with exceptions disabled
        run: |
          xmake f -m release --no_except=y -y
          xmake -y
