name: Release
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-release
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - "v**"
    branches: [master]
jobs:
  build-checks:
    uses: ./.github/workflows/build.yml
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
  release-packages:
    needs: [build-checks]
    name: release
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build packages
        run: |
          xmake f -m release -y
          xmake package -y
      - name: Add artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/packages/**/*
  docs:
    uses: ./.github/workflows/docs.yml
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    with:
      subdir: ${{github.ref_name}}
    permissions:
      contents: write
      pages: write
  docs-latest:
    uses: ./.github/workflows/docs.yml
    needs: [docs]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    with:
      subdir: latest
    permissions:
      contents: write
      pages: write
