name: Release
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-release
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - "v**"
    branches: [master]
jobs:
  build-checks:
    uses: ./.github/workflows/build.yml
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
  release-source:
    needs: [build-checks]
    name: release
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python3 -m pip install meson ninja
      - name: Configure and build
        run: |
          meson setup build
          meson dist -C build/ --allow-dirty --no-tests --include-subprojects
      - name: Add artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/meson-dist/**/*
  docs:
    uses: ./.github/workflows/docs.yml
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    with:
      subdir: ${{github.ref_name}}
    permissions:
      contents: write
      pages: write
  docs-latest:
    uses: ./.github/workflows/docs.yml
    needs: [docs]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    with:
      subdir: latest
    permissions:
      contents: write
      pages: write
